### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by firinael** [1000ch/Sublime-csso#6]
![image](https://user-images.githubusercontent.com/67032657/133534379-fc975e01-4927-44ee-abac-7bb9fec1ed5c.png)

Tried adding stuff to path and etc, seems like this is something that was fixed on the original CSSO repository with #208.

**Comment by 1000ch** [comment]
@firinael thank you for reporting and sorry for bothering you, it seems to be fixed on [`v3.2.0`](https://github.com/1000ch/Sublime-csso/releases/tag/v3.2.0).
